'use strict';

const C5_ID='chapter_5_market_day';
const C5_EVIDENCE='chapter5Evidence';
const C5_TOTAL=10;
const C5_CHAPTER='🛍️ Chapter 5';
const C5_DATA=()=>meqStoryData(C5_ID);

function ensureC5State(){meqEnsureEvidence(C5_EVIDENCE);state.chapter5Scene ||= 1;state.chapter5Complete ||= false;}
function c5SceneData(n){return meqStoryScene(C5_ID,n)||{title:`Scene ${n}`,reward_coins:0};}
function c5SetScene(n){ensureC5State();state.chapter5Scene=n;saveState();}
function c5Award(n){const s=c5SceneData(n);meqAwardStory('chapter5',s.id||`scene${n}`,s.reward_coins||0);}
function c5Record(kind,ok,w=1){meqRecordEvidence(C5_EVIDENCE,kind,ok,w);}
function c5Ratios(){return meqEvidenceRatios(C5_EVIDENCE);}
function c5Visual(id){
  const map={
    shop:{id:'shop',label:'shop',en:'shop',es:'tienda / negocio',img:'market_square.svg'},
    apple:{id:'apple',label:'apple',en:'apple',es:'manzana',img:'market_apple.svg'},
    bread:{id:'bread',label:'bread',en:'bread',es:'pan',img:'market_bread.svg'},
    milk:{id:'milk',label:'milk',en:'milk',es:'leche',img:'market_milk.svg'},
    juice:{id:'juice',label:'juice',en:'juice',es:'jugo',img:'market_juice.svg'},
    water:{id:'water',label:'water',en:'water',es:'agua',visual:'💧'},
    need:{id:'need',label:'need',en:'need',es:'necesitar',visual:'💧😮‍💨'},
    want:{id:'want',label:'want',en:'want',es:'querer',visual:'💜🧃'},
    have:{id:'have',label:'have',en:'have',es:'tener',visual:'👐'},
    more:{id:'more',label:'more',en:'more',es:'más',visual:'➕'},
    one:{id:'one',label:'one',en:'one',es:'uno',visual:'1️⃣'},
    two:{id:'two',label:'two',en:'two',es:'dos',visual:'2️⃣'},
    three:{id:'three',label:'three',en:'three',es:'tres',visual:'3️⃣'}
  };return map[id];
}
function showChapter5Intro(){
  ensureC5State();setActiveNav('story');const complete=!!state.chapter5Complete;
  screen.innerHTML=`<section class="card hero-card scene-card"><div class="eyebrow">${complete?'Chapter 5 complete':'Nueva historia desbloqueada'}</div><h1 class="title">Chapter 5 · Market Day</h1><p class="subtitle">${complete?'El picnic ya está comprado. Podés repetir la historia para fluidez y memoria.':'El camino del bosque termina en un pequeño mercado. Esta vez el inglés sirve para elegir, pedir, contar y conversar.'}</p>${meqSceneFrame({backdrop:'market_square.svg',actors:[{src:'amanda.svg',alt:'Amanda',pos:'left-ground',scale:.59},{src:'milo.svg',alt:'Milo',pos:'right-ground',motion:'gentle-bob',scale:.54},{src:'market_shopkeeper.svg',alt:'shopkeeper',pos:'center-ground',scale:.52}],props:[{src:'market_basket.svg',alt:'basket',pos:'center-letter',motion:'letter-glow',scale:.28}],caption:complete?'The market knows your order.':'A picnic basket is empty…',label:'MARKET DAY'})}${meqGuideVisual(complete?'Repetir ayuda a que las frases salgan cada vez más automáticas. Los premios familiares no se duplican.':'Acá no estudiamos “want” o “have” como gramática: los necesitás para conseguir cosas de verdad.')}<div class="scene-skill-row"><span>👂 escuchar</span><span>🔢 contar</span><span>🧺 elegir</span><span>💬 conversar</span><span>🎤 pedir</span></div><button id="c5Start" class="btn primary wide">${complete?'Jugar de nuevo →':'Entrar al mercado →'}</button>${complete?'<button id="c5Campaign" class="btn secondary wide" style="margin-top:9px">📚 Ver campaña</button>':''}</section>`;
  $('c5Start').onclick=c5Scene1Teach;if(complete)$('c5Campaign').onclick=showCampaign;
}
function c5Scene1Teach(){c5SetScene(1);meqRuntimeTeachCarousel({chapterLabel:C5_CHAPTER,scene:1,total:C5_TOTAL,title:c5SceneData(1).title,items:[c5Visual('shop')],onDone:c5Scene1Game});}
function c5Scene1Game(){
  screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,1,C5_TOTAL,c5SceneData(1).title)}<div class="prompt">Find the shop.</div><button id="c5ShopAudio" class="sound-orb">🔊</button><div class="market-hunt">${meqImg('market_square.svg','','market-hunt-bg')}<button class="market-hotspot market-stall" data-id="shop" aria-label="shop">✨</button><button class="market-hotspot market-road" data-id="road" aria-label="road">🛤️</button><button class="market-hotspot market-tree" data-id="tree" aria-label="tree">🌲</button></div><div id="c5ShopFb" class="feedback"></div>${meqStoryHelp('La palabra SHOP se pega al lugar al que necesitás entrar.','shop = tienda / negocio')}</section>`;
  setTimeout(()=>speak('Find the shop.'),220);$('c5ShopAudio').onclick=()=>speak('Find the shop.');document.querySelectorAll('.market-hotspot').forEach(b=>b.onclick=()=>{const ok=b.dataset.id==='shop';c5Record('listening',ok);c5Record('usage',ok);meqRecordUnitTask('shop',ok,{dimensions:['listening','visual','usage'],context:'c5s1:shop_hunt',mode:'hotspot_transfer',distractorId:b.dataset.id});b.classList.add(ok?'correct':'wrong');$('c5ShopFb').className=`feedback ${ok?'good':'soft'}`;$('c5ShopFb').textContent=ok?'🛍️ Found it! El mercado se abre.':'Ese lugar no es el shop. Escuchá otra vez.';if(ok){playSfx('success');c5Award(1);setTimeout(c5Scene2,780)}else{playSfx('retry');speak('shop',true)}});
}
function c5Scene2(){c5SetScene(2);session={c5QtyRound:0,c5QtyTasks:[{n:1,audio:'One apple.'},{n:2,audio:'Two apples.'},{n:3,audio:'Three apples.'}]};renderC5Quantity();}
function renderC5Quantity(){
  const t=session.c5QtyTasks[session.c5QtyRound];if(!t){c5Award(2);return c5Scene3();}session.c5QtyCount=0;
  screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,2,C5_TOTAL,c5SceneData(2).title)}<span class="game-label">🔢 Escuchá y construí</span><div class="prompt">El shopkeeper hace un pedido.</div><button id="c5QtyAudio" class="sound-orb">🔊</button><div class="market-basket-board"><div class="basket-art">${meqImg('market_basket.svg','basket')}</div><div id="c5ApplePile" class="basket-items"></div><div id="c5QtyCount" class="basket-count">0</div></div><div class="qty-controls"><button id="c5QtyMinus" class="btn secondary">−</button><button id="c5QtyPlus" class="btn primary">+ 🍎</button><button id="c5QtyCheck" class="btn green">✓ Listo</button></div><div id="c5QtyFb" class="feedback"></div>${meqStoryHelp('Contá con los ojos y con la mano. El número se vuelve una cantidad, no una traducción.')}</section>`;
  const draw=()=>{$('c5QtyCount').textContent=session.c5QtyCount;$('c5ApplePile').innerHTML=Array.from({length:session.c5QtyCount},()=>meqImg('market_apple.svg','apple','basket-mini-item')).join('')};draw();setTimeout(()=>speak(t.audio),220);$('c5QtyAudio').onclick=()=>speak(t.audio);$('c5QtyPlus').onclick=()=>{session.c5QtyCount=Math.min(3,session.c5QtyCount+1);draw()};$('c5QtyMinus').onclick=()=>{session.c5QtyCount=Math.max(0,session.c5QtyCount-1);draw()};$('c5QtyCheck').onclick=()=>{const ok=session.c5QtyCount===t.n;c5Record('listening',ok);c5Record('usage',ok);meqRecordTextUnits(t.audio,ok,{dimensions:['listening','usage'],context:`c5s2:quantity:${session.c5QtyRound}`,mode:'quantity_transfer'});$('c5QtyFb').className=`feedback ${ok?'good':'soft'}`;$('c5QtyFb').textContent=ok?'✨ La cantidad coincide con lo que escuchaste.':`Todavía no. Escuchá ${t.audio} otra vez.`;if(ok){playSfx('success');session.c5QtyRound++;setTimeout(renderC5Quantity,720)}else{playSfx('retry');speak(t.audio,true)}};
}
function c5Scene3(){c5SetScene(3);meqRuntimeListenChoices({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:3,total:C5_TOTAL,title:c5SceneData(3).title,tasks:[
  {audio:'Find the bread.',target:'bread',choices:[c5Visual('apple'),c5Visual('bread'),c5Visual('milk'),c5Visual('juice')]},
  {audio:'Take the milk.',target:'milk',choices:[c5Visual('apple'),c5Visual('bread'),c5Visual('milk'),c5Visual('juice')]},
  {audio:'Find the juice.',target:'juice',choices:[c5Visual('apple'),c5Visual('bread'),c5Visual('milk'),c5Visual('juice')]}
],onDone:()=>{c5Award(3);c5Scene4Teach();}});}
function c5Scene4Teach(){c5SetScene(4);meqRuntimeTeachCarousel({chapterLabel:C5_CHAPTER,scene:4,total:C5_TOTAL,title:c5SceneData(4).title,items:[c5Visual('need')],onDone:c5Scene4Game});}
function c5Scene4Game(){
  meqRuntimeListenChoices({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:4,total:C5_TOTAL,title:c5SceneData(4).title,tasks:[
    {audio:'I need water.',target:'water',translation:'need = necesitar',prompt:'Amanda viene cansada del bosque. ¿Qué necesita?',choices:[c5Visual('water'),c5Visual('juice')]},
    {audio:'I want juice.',target:'juice',translation:'want = querer',prompt:'Ahora elige por gusto.',choices:[c5Visual('water'),c5Visual('juice')]}
  ],onDone:()=>{c5Award(4);c5Scene5();}});
}
function c5Scene5(){
  c5SetScene(5);meqDialogueStart({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:5,total:C5_TOTAL,title:c5SceneData(5).title,turns:[
    {speaker:'milo',kind:'listen',say:'Do you have milk?',prompt:'Milo modela una pregunta útil. Escuchala antes de leer.',translation:'Do you have milk? = ¿Tenés leche?'},
    {speaker:'shopkeeper',kind:'choice',say:'Yes.',prompt:'El estante de leche está lleno. ¿Qué respuesta escuchaste?',target:'yes',choices:[{id:'yes',visual:'✅'},{id:'no',visual:'❌'}],choiceText:{yes:'Yes.',no:'No.'}},
    {speaker:'player',kind:'voice',say:'Ask for milk.',targetPhrase:'Do you have milk?',prompt:'Ahora hacé vos la pregunta.'},
    {speaker:'shopkeeper',kind:'listen',say:'Yes.',prompt:'La conversación respondió.'}
  ],onDone:()=>{c5Award(5);c5Scene6();}});
}
function c5Scene6(){c5SetScene(6);session={c5MoreCount:1,c5MoreGoal:3};renderC5More();}
function renderC5More(){
  screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,6,C5_TOTAL,c5SceneData(6).title)}<span class="game-label">➕ Acción + cantidad</span><div class="prompt">More, please.</div><button id="c5MoreAudio" class="sound-orb">🔊</button><div class="market-basket-board"><div class="basket-art">${meqImg('market_basket.svg','basket')}</div><div id="c5MorePile" class="basket-items">${Array.from({length:session.c5MoreCount},()=>meqImg('market_apple.svg','apple','basket-mini-item')).join('')}</div><div class="basket-count">${session.c5MoreCount}</div></div><button id="c5MoreAdd" class="btn primary wide">➕ Add one</button><div id="c5MoreFb" class="feedback"></div>${meqStoryHelp('MORE no se explica: cada vez que lo escuchás, la cantidad aumenta.','more = más')}</section>`;
  setTimeout(()=>speak('More, please.'),220);$('c5MoreAudio').onclick=()=>speak('More, please.');$('c5MoreAdd').onclick=()=>{session.c5MoreCount++;const ok=session.c5MoreCount<=session.c5MoreGoal;c5Record('listening',ok,.6);c5Record('usage',ok,.8);if(session.c5MoreCount<session.c5MoreGoal){$('c5MoreFb').className='feedback good';$('c5MoreFb').textContent='More…';playSfx('success');setTimeout(renderC5More,450)}else if(session.c5MoreCount===session.c5MoreGoal){$('c5MoreFb').className='feedback good';$('c5MoreFb').textContent='Three apples. Stop.';playSfx('success');c5Award(6);setTimeout(c5Scene7,700)}else{$('c5MoreFb').className='feedback soft';$('c5MoreFb').textContent='Too many. Volvemos a tres.';session.c5MoreCount=2;playSfx('retry');setTimeout(renderC5More,650)}};
}
function c5Scene7(){
  c5SetScene(7);screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,7,C5_TOTAL,c5SceneData(7).title)}<span class="game-label">🧩 Construí un pedido</span><div class="market-order-cue"><div>${meqImg('market_apple.svg','apple')} ${meqImg('market_apple.svg','apple')}</div><strong>🙏</strong></div><div class="prompt">Escuchá el pedido completo.</div><button id="c5OrderAudio" class="sound-orb">🔊</button><div class="order-chunks"><button data-id="correct">I want · two apples · please.</button><button data-id="wrong1">Two · want · apples I.</button><button data-id="wrong2">Please · apple · three.</button></div><div id="c5OrderFb" class="feedback"></div>${meqStoryHelp('No explicamos el orden gramatical. Elegís el chunk que coincide con la situación y el sonido.')}</section>`;
  const phrase='I want two apples, please.';setTimeout(()=>speak(phrase),220);$('c5OrderAudio').onclick=()=>speak(phrase);document.querySelectorAll('.order-chunks button').forEach(b=>b.onclick=()=>{const ok=b.dataset.id==='correct';c5Record('listening',ok);c5Record('usage',ok);meqRecordTextUnits(phrase,ok,{dimensions:['listening','usage'],context:'c5s7:order_build',mode:'chunk_transfer'});b.classList.add(ok?'correct':'wrong');$('c5OrderFb').className=`feedback ${ok?'good':'soft'}`;$('c5OrderFb').textContent=ok?'✨ Ese pedido suena y significa lo mismo.':'Escuchalo otra vez como una sola frase.';if(ok){playSfx('success');setTimeout(()=>meqRuntimeVoicePrompt({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:7,total:C5_TOTAL,title:c5SceneData(7).title,target:phrase,intro:'Ahora pedilo vos:',onPass:()=>{c5Award(7);c5Scene8()},onFallback:()=>{c5Award(7);c5Scene8()}}),650)}else{playSfx('retry');speak(phrase,true)}});
}
function c5Scene8(){
  c5SetScene(8);screen.innerHTML=`<section class="card scene-card">${meqStoryHeader(C5_CHAPTER,8,C5_TOTAL,c5SceneData(8).title)}${meqSceneFrame({backdrop:'market_square.svg',actors:[{src:'market_shopkeeper.svg',alt:'shopkeeper',pos:'right-ground',scale:.57},{src:'amanda.svg',alt:'Amanda',pos:'left-ground',scale:.55}],caption:'What do you want?'})}<div class="prompt">What do you want?</div><button id="c5WantAudio" class="sound-orb">🔊</button><div class="runtime-choice-grid"><button class="runtime-choice c5-want-choice" data-id="juice">${meqImg('market_juice.svg','juice')}</button><button class="runtime-choice c5-want-choice" data-id="milk">${meqImg('market_milk.svg','milk')}</button></div><div id="c5WantFb" class="feedback"></div></section>`;
  setTimeout(()=>speak('What do you want?'),220);$('c5WantAudio').onclick=()=>speak('What do you want?');document.querySelectorAll('.c5-want-choice').forEach(b=>b.onclick=()=>{const item=b.dataset.id,phrase=`I want ${item}, please.`;c5Record('listening',true);c5Record('usage',true);meqRecordUnitTask('want',true,{dimensions:['listening','usage'],context:'c5s8:free_choice',mode:'meaningful_choice'});meqRecordUnitTask(item,true,{dimensions:['visual','usage'],context:`c5s8:item:${item}`,mode:'personal_choice'});session.c5WantItem=item;meqRuntimeVoicePrompt({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:8,total:C5_TOTAL,title:c5SceneData(8).title,target:phrase,intro:'Contestale al shopkeeper:',onPass:()=>c5Scene8Thanks(item),onFallback:()=>c5Scene8Thanks(item)});});
}
function c5Scene8Thanks(item){
  screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,8,C5_TOTAL,c5SceneData(8).title)}<div class="dialogue-stage"><div class="dialogue-bubble npc"><small>Shopkeeper</small><b>Here.</b></div><div class="dialogue-bubble player"><small>You</small><b>Thank you.</b></div></div><div class="big-emoji">${item==='juice'?'🧃':'🥛'}✨</div><button id="c5ThanksAudio" class="sound-orb">🔊</button><button id="c5ThanksNext" class="btn primary wide">Thank you →</button></section>`;setTimeout(()=>speak('Here.'),180);$('c5ThanksAudio').onclick=()=>speak('Here. Thank you.');$('c5ThanksNext').onclick=()=>{speak('Thank you.');c5Award(8);c5Scene9();};
}
function c5Scene9(){c5SetScene(9);session={c5MemoryRound:0,c5Memory:[
  {audio:'Two apples and one milk.',target:'a',choices:[{id:'a',visual:'🍎🍎 + 🥛'},{id:'b',visual:'🍎 + 🥛🥛'},{id:'c',visual:'🍞🍞 + 🧃'}]},
  {audio:'One bread and two juices.',target:'c',choices:[{id:'a',visual:'🍞🍞 + 🧃'},{id:'b',visual:'🍎 + 🥛🥛'},{id:'c',visual:'🍞 + 🧃🧃'}]}
]};renderC5Memory();}
function renderC5Memory(){
  const t=session.c5Memory[session.c5MemoryRound];if(!t){c5Award(9);return c5Scene10Intro();}screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,9,C5_TOTAL,c5SceneData(9).title)}<span class="game-label">🧠 Escucha + memoria</span><div class="prompt">Escuchá el pedido. Después elegí la canasta.</div><button id="c5MemoryAudio" class="sound-orb">🔊</button><div class="runtime-choice-grid">${shuffle(t.choices).map(c=>`<button class="runtime-choice c5-memory-choice" data-id="${c.id}"><span class="runtime-choice-emoji">${c.visual}</span></button>`).join('')}</div><div id="c5MemoryFb" class="feedback"></div><button id="c5MemoryReplay" class="btn secondary wide">🔁 Repetir pedido</button></section>`;
  let replays=0;setTimeout(()=>speak(t.audio),220);$('c5MemoryAudio').onclick=()=>speak(t.audio);$('c5MemoryReplay').onclick=()=>{replays++;const e=meqEnsureEvidence(C5_EVIDENCE);e.helpUses=(e.helpUses||0)+1;saveState();speak(t.audio,true)};document.querySelectorAll('.c5-memory-choice').forEach(b=>b.onclick=()=>{const ok=b.dataset.id===t.target;c5Record('listening',ok,1.4);c5Record('usage',ok,1.2);meqRecordTextUnits(t.audio,ok,{dimensions:['listening','usage'],context:`c5s9:memory:${session.c5MemoryRound}`,mode:'order_memory',helpLevel:replays?2:0,weight:1.2});b.classList.add(ok?'correct':'wrong');$('c5MemoryFb').className=`feedback ${ok?'good':'soft'}`;$('c5MemoryFb').textContent=ok?(replays?'✨ Correcto. Lo resolviste con una repetición.':'🌟 Correcto de memoria.'):'No coincide. Escuchá una vez más.';if(ok){playSfx('success');session.c5MemoryRound++;setTimeout(renderC5Memory,760)}else{playSfx('retry');speak(t.audio,true)}});
}
function c5Scene10Intro(){
  c5SetScene(10);const r=c5Ratios();screen.innerHTML=`<section class="card hero-card scene-card">${meqStoryHeader(C5_CHAPTER,10,C5_TOTAL,c5SceneData(10).title)}<h1 class="title">Buy the Picnic</h1><p class="subtitle">Una conversación completa. No aparece vocabulario nuevo.</p><div class="mastery-grid"><div><b>${pct(r.listening)}%</b><small>escucha</small></div><div><b>${pct(r.usage)}%</b><small>uso</small></div><div><b>${pct(r.speaking)}%</b><small>voz</small></div><div><b>${meqEnsureEvidence(C5_EVIDENCE).helpUses||0}</b><small>ayudas</small></div></div>${meqGuideVisual('El final mezcla saludo, pedido, cantidad, una pregunta y despedida. Si algo sale flojo, reforzamos sólo eso.')}<button id="c5BossStart" class="btn primary wide">Empezar compra final →</button></section>`;$('c5BossStart').onclick=c5BossStart;
}
function c5BossStart(){
  session={c5BossScore:0};meqDialogueStart({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:10,total:C5_TOTAL,title:c5SceneData(10).title,turns:[
    {speaker:'shopkeeper',kind:'listen',say:'Hello.',prompt:'Entrás al puesto.'},
    {speaker:'player',kind:'voice',say:'Order the apples.',targetPhrase:'I want two apples, please.',prompt:'Pedí dos manzanas.'},
    {speaker:'player',kind:'voice',say:'Ask about milk.',targetPhrase:'Do you have milk?',prompt:'Preguntá si tiene leche.'},
    {speaker:'shopkeeper',kind:'choice',say:'Yes.',prompt:'¿Qué respuesta escuchaste?',target:'yes',choices:[{id:'yes',visual:'✅'},{id:'no',visual:'❌'}],choiceText:{yes:'Yes.',no:'No.'}},
    {speaker:'player',kind:'voice',say:'Ask for one milk.',targetPhrase:'One milk, please.',prompt:'Pedí una leche.'},
    {speaker:'shopkeeper',kind:'listen',say:'Here.',prompt:'El shopkeeper entrega la canasta.'},
    {speaker:'player',kind:'voice',say:'Finish politely.',targetPhrase:'Thank you. Goodbye.',prompt:'Cerrá la conversación.'}
  ],onDone:c5BossBasket});
}
function c5BossBasket(){
  screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,10,C5_TOTAL,c5SceneData(10).title)}<span class="game-label">🧺 Última comprobación</span><div class="prompt">Armá la canasta que acabás de pedir.</div><div class="runtime-choice-grid"><button class="runtime-choice c5-boss-basket" data-id="correct">🍎🍎 + 🥛</button><button class="runtime-choice c5-boss-basket" data-id="wrong1">🍎 + 🥛🥛</button><button class="runtime-choice c5-boss-basket" data-id="wrong2">🍞 + 🧃🧃</button></div><div id="c5BossBasketFb" class="feedback"></div></section>`;document.querySelectorAll('.c5-boss-basket').forEach(b=>b.onclick=()=>{const ok=b.dataset.id==='correct';c5Record('listening',ok,1.5);c5Record('usage',ok,1.5);meqRecordTextUnits('I want two apples please. One milk please.',ok,{dimensions:['listening','usage'],context:'c5boss:basket_transfer',mode:'global_comprehension',weight:1.3});if(ok)session.c5BossScore=1;b.classList.add(ok?'correct':'wrong');$('c5BossBasketFb').className=`feedback ${ok?'good':'soft'}`;$('c5BossBasketFb').textContent=ok?'✨ Es exactamente lo que pediste.':'La canasta no coincide con la conversación.';if(ok){playSfx('success');setTimeout(finishC5Boss,700)}else{playSfx('retry')}});
}
function finishC5Boss(){
  const r=c5Ratios(),overall=.43*r.listening+.39*r.usage+.18*Math.max(r.speaking,.62);const pass=session.c5BossScore===1&&overall>=.80&&r.listening>=.75&&r.usage>=.73;
  if(pass){state.chapter5Complete=true;saveState();c5Award(10);}screen.innerHTML=`<section class="card reward-card scene-card"><div class="big-emoji">${pass?'🧺✨🥛🍎':'🦊🛠️'}</div><div class="eyebrow">Market Day</div><h1 class="title">${pass?'Picnic ready!':'Una habilidad necesita refuerzo'}</h1><p class="subtitle">${pass?'Usaste inglés para conseguir cosas, contar y completar una conversación.':'No repetimos la historia. Milo refuerza sólo el punto más bajo y volvemos al final.'}</p><div class="mastery-grid"><div><b>${pct(r.listening)}%</b><small>escucha</small></div><div><b>${pct(r.usage)}%</b><small>uso</small></div><div><b>${pct(r.speaking)}%</b><small>voz</small></div><div><b>${meqEnsureEvidence(C5_EVIDENCE).helpUses||0}</b><small>ayudas</small></div></div><button id="c5ResultNext" class="btn primary wide">${pass?'Ver final →':'Refuerzo rápido →'}</button><button id="c5ResultCampaign" class="btn secondary wide" style="margin-top:9px">Ver campaña</button></section>`;$('c5ResultNext').onclick=()=>pass?c5Ending():c5Repair();$('c5ResultCampaign').onclick=showCampaign;
}
function c5Repair(){
  const r=c5Ratios(),skill=r.speaking<.62?'speaking':r.listening<=r.usage?'listening':'usage';if(skill==='speaking')return meqRuntimeVoicePrompt({stateKey:C5_EVIDENCE,chapterLabel:C5_CHAPTER,scene:10,total:C5_TOTAL,title:"Milo's Quick Repair",target:'I want two apples, please.',intro:'Una frase y volvemos al final:',onPass:c5Scene10Intro,onFallback:c5Scene10Intro});
  session={c5Repair:0,c5RepairSkill:skill,tasks:[{audio:'Two apples.',target:'two',choices:[c5Visual('one'),c5Visual('two'),c5Visual('three')]},{audio:'Find the milk.',target:'milk',choices:[c5Visual('milk'),c5Visual('juice')]},{audio:'More, please.',target:'more',choices:[c5Visual('more'),{id:'stop',visual:'🛑'}]}]};renderC5Repair();
}
function renderC5Repair(){const t=session.tasks[session.c5Repair];if(!t)return c5Scene10Intro();screen.innerHTML=`<section class="card word-stage scene-card">${meqStoryHeader(C5_CHAPTER,10,C5_TOTAL,"Milo's Quick Repair")}<span class="game-label">🛠️ Sólo reforzamos ${session.c5RepairSkill}</span><div class="prompt">Tres pistas y volvés al mercado.</div><button id="c5RepairAudio" class="sound-orb">🔊</button><div class="runtime-choice-grid">${shuffle(t.choices).map(c=>`<button class="runtime-choice c5-repair-choice" data-id="${c.id}">${meqChoiceVisual(c)}</button>`).join('')}</div><div id="c5RepairFb" class="feedback"></div></section>`;setTimeout(()=>speak(t.audio),220);$('c5RepairAudio').onclick=()=>speak(t.audio);document.querySelectorAll('.c5-repair-choice').forEach(b=>b.onclick=()=>{const ok=b.dataset.id===t.target;c5Record(session.c5RepairSkill,ok,2);meqRecordUnitTask(t.target,ok,{dimensions:[session.c5RepairSkill==='usage'?'usage':'listening'],context:`c5repair:${session.c5Repair}:${t.target}`,mode:'adaptive_repair',distractorId:b.dataset.id,weight:1.3});if(session.c5RepairSkill!=='listening')c5Record('listening',true,.3);b.classList.add(ok?'correct':'wrong');$('c5RepairFb').className=`feedback ${ok?'good':'soft'}`;$('c5RepairFb').textContent=ok?'✨ Reforzado.':'La repetimos lenta.';if(!ok)speak(t.audio,true);setTimeout(()=>{session.c5Repair++;renderC5Repair()},720)});}
function c5Ending(){
  screen.innerHTML=`<section class="card hero-card scene-card"><div class="eyebrow">Chapter 5 complete</div><h1 class="title">Market Day · End</h1>${meqSceneFrame({backdrop:'market_square.svg',actors:[{src:'amanda.svg',alt:'Amanda',pos:'left-ground',scale:.58},{src:'milo.svg',alt:'Milo',pos:'right-ground',scale:.54},{src:'market_shopkeeper.svg',alt:'shopkeeper',pos:'center-ground',scale:.5}],props:[{src:'market_basket.svg',alt:'picnic basket',pos:'center-letter',motion:'letter-glow',scale:.3}],caption:'The basket is full. A tiny silver key is underneath.',label:'STORY COMPLETE'})}<p class="subtitle">Debajo de la canasta aparece una llave plateada con el dibujo de una habitación. Al volver a la academia, una puerta que antes no estaba empieza a brillar.</p>${meqGuideVisual('La próxima historia va a llevar el inglés a espacios cotidianos: bedroom, bathroom, kitchen, light, bed, inside y outside.')}<div class="chapter-hook"><span>🌙🚪</span><div><b>Next: Chapter 6</b><strong>The Midnight Room</strong><small>home · rooms · day/night · inside/outside</small></div></div><button id="c5EndCampaign" class="btn primary wide" style="margin-top:14px">Volver a la campaña →</button></section>`;$('c5EndCampaign').onclick=showCampaign;
}

if(typeof SONGS!=='undefined'){
  SONGS.market={id:'market',title:'Market Count Beat',unlock:()=>!!state.chapter4Complete,icon:'🛍️🎵',phrases:[
    {text:'One apple.',visual:'🍎',words:['one','apple']},{text:'Two apples.',visual:'🍎🍎',words:['two','apple']},{text:'Three apples.',visual:'🍎🍎🍎',words:['three','apple']},{text:'I want juice, please.',visual:'🧃🙏',words:['i','want','juice','please']},{text:'Do you have milk?',visual:'🥛❓',words:['do','you','have','milk']}
  ]};
}

showCampaign = function(){
  ensureC2State();ensureC3State();ensureC4State();ensureC5State();const c1=!!state.chapter1Complete,c2=!!state.chapter2Complete,c3=!!state.chapter3Complete,c4=!!state.chapter4Complete,c5=!!state.chapter5Complete;
  screen.innerHTML=`<section class="card hero-card"><div class="eyebrow">Tu aventura</div><h1 class="title">Cada historia usa el inglés de la anterior</h1><p class="subtitle">Los capítulos tienen principio, problema y final. El idioma aparece porque la aventura lo necesita.</p>${meqGuideVisual(c5?'Cinco historias completas. Ya usamos inglés para saludar, buscar, orientarnos, leer mensajes y pedir cosas.':c4?'Market Day está listo. Ahora el inglés entra en una conversación cotidiana.':c3?'El acertijo del bosque ya está desbloqueado.':'Seguí el capítulo activo.')}<div class="chapter-grid">
  <button class="chapter-card ${c1?'done':'active'}" id="campaignC1"><span>✉️</span><div><b>Chapter 1</b><strong>The Magic Letter</strong><small>${c1?'✓ Terminado':'En curso'}</small></div></button>
  <button class="chapter-card ${c1?(c2?'done':'active'):'locked'}" id="campaignC2" ${c1?'':'disabled'}><span>🧪</span><div><b>Chapter 2</b><strong>Potion Mystery</strong><small>${!c1?'🔒 Bloqueado':c2?'✓ Terminado':'Listo para jugar'}</small></div></button>
  <button class="chapter-card ${c2?(c3?'done':'active'):'locked'}" id="campaignC3" ${c2?'':'disabled'}><span>🦉</span><div><b>Chapter 3</b><strong>Owl Message</strong><small>${!c2?'🔒 Bloqueado':c3?'✓ Terminado':'Listo para jugar'}</small></div></button>
  <button class="chapter-card ${c3?(c4?'done':'active'):'locked'}" id="campaignC4" ${c3?'':'disabled'}><span>🌲</span><div><b>Chapter 4</b><strong>Forest Riddle</strong><small>${!c3?'🔒 Bloqueado':c4?'✓ Terminado':'Listo para jugar'}</small></div></button>
  <button class="chapter-card ${c4?(c5?'done':'active'):'locked'}" id="campaignC5" ${c4?'':'disabled'}><span>🛍️</span><div><b>Chapter 5</b><strong>Market Day</strong><small>${!c4?'🔒 Bloqueado':c5?'✓ Terminado':'Listo para jugar'}</small></div></button>
  <button class="chapter-card locked" disabled><span>🌙</span><div><b>Chapter 6</b><strong>The Midnight Room</strong><small>${c5?'🔒 Próximo':'🔒 Bloqueado'}</small></div></button>
  </div></section>`;
  $('campaignC1').onclick=showChapter1Intro;if(c1)$('campaignC2').onclick=showChapter2Intro;if(c2)$('campaignC3').onclick=showChapter3Intro;if(c3)$('campaignC4').onclick=showChapter4Intro;if(c4)$('campaignC5').onclick=showChapter5Intro;setActiveNav('story');
};
showMap = function(){
  ensureC2State();ensureC3State();ensureC4State();ensureC5State();screen.innerHTML=`<section class="card"><div class="eyebrow">Prólogo</div><h1 class="title">Before the Letter</h1><p class="subtitle">Diez escalones. La historia empieza cuando existe una base mínima real.</p><div class="quest-map">${MAP.map((n,i)=>{const step=i+1,unlock=step<=state.unlockedStep,current=step===state.currentStep,d=stageData(step);return `<button class="map-node ${unlock?'unlocked':'locked'} ${current?'current':''}" data-step="${step}" ${unlock?'':'disabled'}><div class="node-num">${d.mastered?'✓':step}</div><div><div class="node-title">${n[0]}</div><div class="node-sub">${n[1]}</div></div><div class="node-badge">${unlock?n[2]:'🔒'}</div></button>`}).join('')}</div></section><section class="card"><div class="eyebrow">Campaña</div><h2 style="margin:5px 0">Historias</h2><div class="chapter-grid compact"><button class="chapter-card ${state.chapter1Complete?'done':state.phase0Complete?'active':'locked'}" id="mapC1" ${state.phase0Complete?'':'disabled'}><span>✉️</span><div><b>Ch. 1</b><strong>The Magic Letter</strong></div></button><button class="chapter-card ${state.chapter2Complete?'done':state.chapter1Complete?'active':'locked'}" id="mapC2" ${state.chapter1Complete?'':'disabled'}><span>🧪</span><div><b>Ch. 2</b><strong>Potion Mystery</strong></div></button><button class="chapter-card ${state.chapter3Complete?'done':state.chapter2Complete?'active':'locked'}" id="mapC3" ${state.chapter2Complete?'':'disabled'}><span>🦉</span><div><b>Ch. 3</b><strong>Owl Message</strong></div></button><button class="chapter-card ${state.chapter4Complete?'done':state.chapter3Complete?'active':'locked'}" id="mapC4" ${state.chapter3Complete?'':'disabled'}><span>🌲</span><div><b>Ch. 4</b><strong>Forest Riddle</strong></div></button><button class="chapter-card ${state.chapter5Complete?'done':state.chapter4Complete?'active':'locked'}" id="mapC5" ${state.chapter4Complete?'':'disabled'}><span>🛍️</span><div><b>Ch. 5</b><strong>Market Day</strong></div></button></div></section>`;document.querySelectorAll('.map-node.unlocked').forEach(b=>b.onclick=()=>startStep(Number(b.dataset.step)));if(state.phase0Complete)$('mapC1').onclick=showChapter1Intro;if(state.chapter1Complete)$('mapC2').onclick=showChapter2Intro;if(state.chapter2Complete)$('mapC3').onclick=showChapter3Intro;if(state.chapter3Complete)$('mapC4').onclick=showChapter4Intro;if(state.chapter4Complete)$('mapC5').onclick=showChapter5Intro;setActiveNav('map');
};
const c5OldC4Ending=c4Ending;c4Ending=function(){if(!state.chapter4Complete)return c5OldC4Ending();screen.innerHTML=`<section class="card hero-card scene-card"><div class="eyebrow">Chapter 4 complete</div><h1 class="title">Forest Riddle · End</h1>${meqSceneFrame({backdrop:'forest_night.svg',actors:[{src:'amanda.svg',alt:'Amanda',pos:'left-ground',scale:.58},{src:'milo.svg',alt:'Milo',pos:'right-ground',scale:.55}],props:[{src:'road_rune.svg',alt:'road',pos:'center-letter',motion:'letter-glow',scale:.36}],caption:'The road reaches a small market.'})}<p class="subtitle">Se escuchan voces, números y pedidos. El picnic de la clase todavía está vacío.</p>${meqGuideVisual('Ahora el vocabulario de comida vuelve en otro contexto, combinado con cantidades y conversación.')}<button id="c4ToC5" class="btn primary wide">Empezar Chapter 5 →</button></section>`;$('c4ToC5').onclick=showChapter5Intro;};
storyRoute=function(){if(!state.phase0Complete)return state.introSeen?startStep(state.currentStep):intro();if(!state.chapter1Complete)return showChapter1Intro();if(!state.chapter2Complete)return showChapter2Intro();if(!state.chapter3Complete)return showChapter3Intro();if(!state.chapter4Complete)return showChapter4Intro();if(!state.chapter5Complete)return showChapter5Intro();return showCampaign();};
qCurrentAdventure=function(){if(!state.phase0Complete)return {eyebrow:'Prólogo',title:'Before the Letter',text:`Escalón ${state.currentStep} de 10`,icon:'🦉✉️',action:()=>state.introSeen?startStep(state.currentStep):intro()};if(!state.chapter1Complete)return {eyebrow:'Chapter 1',title:'The Magic Letter',text:'Tu carta ya llegó',icon:'✉️✨',action:showChapter1Intro};if(!state.chapter2Complete)return {eyebrow:'Chapter 2',title:'Potion Mystery',text:'Hay una botella fuera de lugar',icon:'🧪🔎',action:showChapter2Intro};if(!state.chapter3Complete)return {eyebrow:'Chapter 3',title:'Owl Message',text:'Un papel azul espera en el aula',icon:'🦉📄',action:showChapter3Intro};if(!state.chapter4Complete)return {eyebrow:'Chapter 4',title:'Forest Riddle',text:'El bosque necesita direcciones',icon:'🌲🧭',action:showChapter4Intro};if(!state.chapter5Complete)return {eyebrow:'Chapter 5',title:'Market Day',text:'El picnic necesita comida',icon:'🛍️🧺',action:showChapter5Intro};return {eyebrow:'Campaña',title:'Cinco historias completadas',text:'Una llave plateada apareció bajo la canasta',icon:'🌙🔑',action:showCampaign};};
const c5OldUpdateHud=updateHud;updateHud=function(){c5OldUpdateHud();ensureC5State();const l=$('levelText');if(l)l.textContent=(state.chapter5Complete?'Ch. 5 ✓':state.chapter4Complete?'Ch. 5':state.chapter3Complete?'Ch. 4':state.chapter2Complete?'Ch. 3':state.chapter1Complete?'Ch. 2':state.phase0Complete?'Ch. 1':`Step ${state.currentStep}`)+` · ${state.totalXp||0} XP`;const sub=$('headerSubtitle');if(sub)sub.textContent=state.chapter5Complete?'The Midnight Room · next':state.chapter4Complete?'Market Day':state.chapter3Complete?'Forest Riddle':state.chapter2Complete?'Owl Message':state.chapter1Complete?'Potion Mystery':state.phase0Complete?'The Magic Letter':'Before the Letter · Zero English';};
window.MEQ_BUILD='1.9.0';updateHud();if(state.lastRoute==='home')showHome();
